<a href="https://colab.research.google.com/github/owais8-lang/231A057-NLP_experiments/blob/main/NLPexp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Ansari Mohd Owais 231A057
documents = [
    "Artificial intelligence (AI) is transforming many industries.",
    "Machine learning is a key part of artificial intelligence.",
    "Deep learning models are advanced forms of machine learning.",
    "Data is crucial for training effective machine learning models.",
    "AI systems learn from vast amounts of data to improve their intelligence."
]

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [3]:
for i, document in enumerate (documents):
 print (f" D{i + 1}: {document}")

 D1: Artificial intelligence (AI) is transforming many industries.
 D2: Machine learning is a key part of artificial intelligence.
 D3: Deep learning models are advanced forms of machine learning.
 D4: Data is crucial for training effective machine learning models.
 D5: AI systems learn from vast amounts of data to improve their intelligence.

In [4]:
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

(5, 21)

In [5]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 31 stored elements and shape (5, 21)>
  Coords	Values
  (0, 3)	0.4166072657167828
  (0, 11)	0.345821664219199
  (0, 1)	0.4166072657167828
  (0, 19)	0.5163739676148649
  (0, 10)	0.5163739676148649
  (1, 3)	0.4660778481185906
  (1, 11)	0.38688671647327205
  (1, 15)	0.38688671647327205
  (1, 14)	0.38688671647327205
  (1, 12)	0.5776914793752232
  (2, 15)	0.2758682887636216
  (2, 14)	0.5517365775272433
  (2, 6)	0.41192099150185657
  (2, 16)	0.3323352622782266
  (2, 0)	0.41192099150185657
  (2, 8)	0.41192099150185657
  (3, 15)	0.29372019905663493
  (3, 14)	0.29372019905663493
  (3, 16)	0.3538412473118289
  (3, 5)	0.3538412473118289
  (3, 4)	0.43857710562449553
  (3, 18)	0.43857710562449553
  (3, 7)	0.43857710562449553
  (4, 11)	0.2577655323419535
  (4, 1)	0.310527085882465
  (4, 5)	0.310527085882465
  (4, 17)	0.3848903189749406
  (4, 13)	0.3848903189749406
  (4, 20)	0.3848903189749406
  (4, 2)	0.3848903189749406
  (4, 9)	0.3848903189749406

In [6]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=["D1","D2","D3","D4","D5"]
)
tfidf_df.round(2)

,advanced,ai,amounts,artificial,crucial,data,deep,effective,forms,improve,...,intelligence,key,learn,learning,machine,models,systems,training,transforming,vast
D1,0.00,0.42,0.00,0.42,0.00,0.00,0.00,0.00,0.00,0.00,...,0.35,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.52,0.00
D2,0.00,0.00,0.00,0.47,0.00,0.00,0.00,0.00,0.00,0.00,...,0.39,0.58,0.00,0.39,0.39,0.00,0.00,0.00,0.00,0.00
D3,0.41,0.00,0.00,0.00,0.00,0.00,0.41,0.00,0.41,0.00,...,0.00,0.00,0.00,0.55,0.28,0.33,0.00,0.00,0.00,0.00
D4,0.00,0.00,0.00,0.00,0.44,0.35,0.00,0.44,0.00,0.00,...,0.00,0.00,0.00,0.29,0.29,0.35,0.00,0.44,0.00,0.00
D5,0.00,0.31,0.38,0.00,0.00,0.31,0.00,0.00,0.00,0.38,...,0.26,0.00,0.38,0.00,0.00,0.00,0.38,0.00,0.00,0.38

In [7]:
print(vectorizer.get_feature_names_out())

['advanced' 'ai' 'amounts' 'artificial' 'crucial' 'data' 'deep'
 'effective' 'forms' 'improve' 'industries' 'intelligence' 'key' 'learn'
 'learning' 'machine' 'models' 'systems' 'training' 'transforming' 'vast']

In [8]:
similarity_matrix = cosine_similarity(tfidf_matrix)
similarity_matrix

array([[1.        , 0.32796523, 0.        , 0.        , 0.21850875],
       [0.32796523, 1.        , 0.32018933, 0.22727289, 0.09972606],
       [0.        , 0.32018933, 1.        , 0.36067819, 0.        ],
       [0.        , 0.22727289, 0.36067819, 1.        , 0.10987729],
       [0.21850875, 0.09972606, 0.        , 0.10987729, 1.        ]])

In [9]:
similarity_df = pd.DataFrame(
similarity_matrix,
index=["D1", "D2", "D3", "D4", "D5"],
columns=["D1", "D2", "D3", "D4", "D5"]
)
similarity_df.round(3)

       D1     D2     D3     D4     D5
D1  1.000  0.328  0.000  0.000  0.219
D2  0.328  1.000  0.320  0.227  0.100
D3  0.000  0.320  1.000  0.361  0.000
D4  0.000  0.227  0.361  1.000  0.110
D5  0.219  0.100  0.000  0.110  1.000

In [10]:
highest_similarity = -1
most_similar_pair = None
for i in range(len(documents)):
  for j in range(i + 1, len(documents)):
    similarity = similarity_matrix[i][j]

    if similarity > highest_similarity:
      highest_similarity = similarity
      most_similar_pair = (i, j)

if most_similar_pair is not None:
  print(f"Most similar documents: D{most_similar_pair[0]+1} and D{most_similar_pair[1]+1}")
  print(f"Similarity: {highest_similarity:.3f}")
else:
  print("No similar documents found (or only one document).")

Most similar documents: D3 and D4
Similarity: 0.361